[[constraint]]
  name = "gopkg.in/BurntSushi/toml.v0"
  version = "0.3.1"

[[constraint]]
  name = "github.com/gaarx/gaarx"
  version = "0.1.8"

[[constraint]]
  branch ="master"
  name = "github.com/zergu1ar/logrus-filename"

[prune]
  go-tests = true
  unused-packages = true